import shutil
import subprocess
from pathlib import Path

import pytest
from typer.testing import CliRunner

from atopile import errors
from atopile.cli.build import _init_python_app
from atopile.cli.common import create_build_contexts

runner = CliRunner(mix_stderr=False)

PROJECT_DIR = Path("test/common/resources/test-project")


@pytest.fixture()
def from_project_dir(monkeypatch: pytest.MonkeyPatch):
    monkeypatch.chdir(PROJECT_DIR)

    yield

    monkeypatch.undo()


@pytest.fixture(autouse=True, scope="session")
def cleanup():
    yield

    # generated by builds
    for pattern in ("*.kicad_pcb", "*.kicad_pro", "fp-lib-table"):
        for path in PROJECT_DIR.glob(pattern):
            path.unlink(missing_ok=True)

    shutil.rmtree(PROJECT_DIR / "build", ignore_errors=True)


@pytest.mark.parametrize(
    "build_name,expected_error",
    [
        ("unconstructable", errors.UserPythonConstructionError),
        ("unimportable", errors.UserPythonModuleError),
    ],
)
def test_build_errors(from_project_dir: None, build_name: str, expected_error):
    build_ctxs = create_build_contexts(
        entry=None, build=[build_name], target=[], option=[]
    )

    (build_ctx,) = build_ctxs

    with pytest.raises(expected_error) as exc_info:
        _init_python_app(build_ctx)

    assert exc_info.value.__cause__ is not None
    assert isinstance(exc_info.value.__cause__, ValueError)
    assert exc_info.value.__cause__.args == (build_name,)


@pytest.mark.parametrize("build_name", ["unconstructable", "unimportable"])
def test_build_error_logging(from_project_dir: None, build_name: str):
    # CLIRunner doesn't give us the fully-formatted log output as seen by the user
    result = subprocess.run(
        ["ato", "build", "-b", build_name], capture_output=True, text=True
    )

    # single error
    assert result.stdout.count("ERROR") == 1

    # single traceback
    assert result.stdout.count("❱") == 1
    assert result.stdout.count("Traceback (most recent call last)") == 1
    assert "another exception occurred" not in result.stdout
    assert "direct cause of the following exception" not in result.stdout

    # including the test exception
    assert f'raise ValueError("{build_name}")' in result.stdout

    # exiting cleanly
    assert result.stdout.strip().endswith(
        "Unfortunately errors ^^^ stopped the build. If you need a hand jump on Discord! \nhttps://discord.gg/mjtxARsr9V 👋"
    )

    # exception groups are unwrapped
    assert "ExceptionGroup" not in result.stdout

    # with a non-zero exit code
    assert result.returncode == 1
