from typing import Callable

Literal = int | float | str | bool

class Node:
    __init__: None
    @staticmethod
    def create(**attrs: Literal) -> Node: ...
    def get_attr(self, *, key: str) -> Literal | None: ...
    def get_dynamic_attrs(self) -> dict[str, Literal]: ...
    def get_uuid(self) -> int: ...
    def get_attrs(self) -> dict[str, Literal]: ...
    def is_same(self, *, other: Node) -> bool: ...

class Edge:
    __init__: None
    Type = int

    @staticmethod
    def create(
        *,
        source: Node,
        target: Node,
        edge_type: Type,
        directional: bool | None = None,
        name: str | None = None,
        **attrs: Literal,
    ) -> Edge: ...
    def source(self) -> Node: ...
    def target(self) -> Node: ...
    def edge_type(self) -> Type: ...
    def directional(self) -> bool | None: ...
    def name(self) -> str | None: ...
    def get_attr(self, *, key: str) -> Literal | None: ...
    def is_same(self, *, other: Edge) -> bool: ...

class BoundNode:
    __init__: None
    def node(self) -> Node: ...
    def g(self) -> GraphView: ...
    def visit_edges_of_type[T](
        self,
        *,
        edge_type: Edge.Type,
        ctx: T,
        f: Callable[[T, BoundEdge], None],
    ) -> None: ...

class BoundEdge:
    __init__: None
    def edge(self) -> Edge: ...
    def g(self) -> GraphView: ...

class GraphView:
    __init__: None
    def insert_node(self, *, node: Node) -> BoundNode: ...
    def insert_edge(self, *, edge: Edge) -> BoundEdge: ...
    def bind(self, *, node: Node) -> BoundNode: ...
    def get_node_count(self) -> int: ...
    @staticmethod
    def create() -> GraphView: ...

class BFSPath:
    __init__: None
    def get_length(self) -> int: ...
    def get_start_node(self) -> BoundNode: ...
    def get_end_node(self) -> BoundNode: ...
    def get_edges(self) -> list[BoundEdge]: ...
