# This file is part of the faebryk project
# SPDX-License-Identifier: MIT

# This file is auto-generated by nanobind.
# Do not edit this file directly; edit the corresponding
# C++ file instead.

def add(arg0: int, arg1: int, /) -> int:
    """A function that adds two numbers"""
