from faebryk.core.zig.gen.faebryk.typegraph import TypeGraph
from faebryk.core.zig.gen.graph.graph import BoundNode, GraphView

class String:
    @staticmethod
    def create_instance(*, g: GraphView, tg: TypeGraph, value: str) -> "String": ...
    @staticmethod
    def bind_instance(*, instance: BoundNode) -> "String": ...
    def get_value(self) -> str: ...
    def get_instance(self) -> BoundNode: ...

class Strings:
    @staticmethod
    def create_instance(*, g: GraphView, tg: TypeGraph) -> "Strings": ...
    @staticmethod
    def bind_instance(*, instance: BoundNode) -> "Strings": ...
    def get_instance(self) -> BoundNode: ...
    def setup_from_values(self, *, values: list[str]) -> "Strings": ...
    def get_values(self) -> list[str]: ...

class Interval:
    min: float
    max: float

class Numbers: ...
class Booleans: ...
