from faebryk.core.zig.gen.faebryk.typegraph import TypeGraph
from faebryk.core.zig.gen.graph.graph import BoundNode, GraphView

class String:
    @staticmethod
    def create_instance(*, g: GraphView, tg: TypeGraph, value: str) -> "String": ...
    def get_value(self) -> str: ...
    def get_instance(self) -> BoundNode: ...

class Strings: ...

class Interval:
    min: float
    max: float

class Numbers: ...
class Booleans: ...
