authors:
  narayan:
    name: Narayan Powderly
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/8122613
    url: https://github.com/napowderly
  matt:
    name: Matt Wildoer
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/4241578
    url: https://github.com/mawildoer
  tim:
    name: Timothee Peter
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/9785003
    url: https://github.com/Timot05