#!/usr/bin/env python3
"""Fetch all available JLCPCB layer stackup options and dump raw JSON responses.

API details and parameter ranges based on:
https://github.com/gsuberland/jlcpcb_autogenerated_stackups (MIT, Graham Sutherland)
"""

import json
import re
import time
from pathlib import Path
from typing import Any

import httpx
import typer
from rich.console import Group
from rich.live import Live
from rich.progress import BarColumn, MofNCompleteColumn, Progress, TimeRemainingColumn
from rich.text import Text

from faebryk.libs.jlcpcb.jlcpcb_impedance_data import (
    COPPER_SPECS,
    SOLDER_MASK,
    TRACE_GEOMETRY,
    material_for_layer_count,
)

API_URL = "https://cart.jlcpcb.com/api/overseas-shop-cart/v1/shoppingCart/getImpedanceTemplateSettings"

# Valid board thicknesses per layer count (from JLCPCB's options)
THICKNESS_MAP: dict[int, list[float]] = {
    4: [0.8, 1.0, 1.2, 1.6, 2.0],
    6: [0.8, 1.0, 1.2, 1.6, 2.0],
    8: [0.8, 1.0, 1.2, 1.6, 2.0],
    10: [1.0, 1.2, 1.6, 2.0],
    12: [1.2, 1.6, 2.0, 2.5],
    14: [1.6, 2.0, 2.5],
    16: [1.6, 2.0, 2.5],
    18: [2.0, 2.5],
    20: [2.0, 2.5],
    22: [2.5, 3.0],
    24: [2.5, 3.2],
    26: [2.5, 3.5],
    28: [3.0, 4.0],
    30: [3.0, 4.0],
    32: [3.0, 3.2, 4.5],
}

OUTER_COPPER_WEIGHTS = [1.0, 2.0]  # oz
INNER_COPPER_WEIGHTS = [0.5, 1.0, 2.0]  # oz

# Max 120 requests/minute = 0.5s minimum between requests
MIN_REQUEST_INTERVAL = 0.5

app = typer.Typer()


def _parse_lamination_content(content_str: str) -> dict[str, Any]:
    """Parse the stringified JSON inside a lamination's content field."""
    return json.loads(content_str)


def _clean_line(content: dict[str, Any]) -> dict[str, Any]:
    """Clean a copper foil (Line) lamination into a normalized layer."""
    return {
        "type": "copper",
        "layer": content.get("LineLayer", ""),
        "material": content.get("lineMaterialType", ""),
        "thickness_mm": content.get("LineThickness", ""),
    }


def _clean_prepreg(content: dict[str, Any]) -> dict[str, Any]:
    """Clean a prepreg lamination into a normalized layer."""
    return {
        "type": "prepreg",
        "material": content.get("preMaterialType", ""),
        "thickness_mm": content.get("preThickness", ""),
    }


def _clean_core(content: dict[str, Any]) -> list[dict[str, Any]]:
    """Clean a core lamination into normalized layers.

    A core block contains up to 3 sub-layers (copper/core/copper).
    """
    layers = []
    for i in range(1, 4):
        layer_name = content.get(f"coreBoardLayer{i}")
        material = content.get(f"coreBoardMaterialType{i}")
        thickness = content.get(f"coreBoardThickness{i}")
        if not layer_name or not material:
            continue
        if material == "Copper":
            layers.append(
                {
                    "type": "copper",
                    "layer": layer_name,
                    "material": material,
                    "thickness_mm": thickness or "",
                }
            )
        elif material == "Core":
            layers.append(
                {
                    "type": "core",
                    "material": material,
                    "thickness_mm": thickness or "",
                }
            )
    return layers


# iaminationType enum from JLCPCB API
_LAMINATION_LINE = 1
_LAMINATION_PREPREG = 2
_LAMINATION_CORE = 3


def clean_data(raw: dict[str, Any]) -> list[dict[str, Any]]:
    """Normalize raw JLCPCB API response into clean stackup data.

    Strips vendor metadata, unpacks stringified content JSON,
    and returns a flat list of stackup templates with ordered layers.
    """
    templates = raw.get("data") or []
    cleaned = []

    for template in templates:
        laminations = sorted(
            template.get("iaminationList") or [],
            key=lambda lamin: lamin.get("sort", 0),
        )

        layers: list[dict[str, Any]] = []
        for lam in laminations:
            content = _parse_lamination_content(lam["content"])
            lam_type = lam["iaminationType"]

            if lam_type == _LAMINATION_LINE:
                layers.append(_clean_line(content))
            elif lam_type == _LAMINATION_PREPREG:
                layers.append(_clean_prepreg(content))
            elif lam_type == _LAMINATION_CORE:
                layers.extend(_clean_core(content))

        cleaned.append(
            {
                "template_name": template.get("templateName", ""),
                "layer_count": template.get("stencilLayer"),
                "board_thickness_mm": template.get("stencilPly"),
                "is_default": template.get("defaultFlag", False),
                "expedited": template.get("expeditedFlag", False),
                "enabled": template.get("enableFlag", True),
                "layers": layers,
            }
        )

    return cleaned


def _parse_thickness_mm(s: str) -> float | None:
    """Parse a thickness string like '0.21040mm' into a float."""
    m = re.match(r"([\d.]+)\s*mm", s)
    return float(m.group(1)) if m else None


def _prepreg_type_name(material: str) -> str:
    """Extract prepreg type from material string like '7628*1' → '7628'."""
    return material.split("*")[0]


def enhance_data(
    templates: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Enhance cleaned stackup data with material properties from impedance data.

    Adds εr (relative permittivity) to prepreg/core layers, copper weight info,
    solder mask properties, and trace geometry rules.
    """
    for template in templates:
        layer_count = template.get("layer_count", 0)
        mat = material_for_layer_count(layer_count)

        # Build lookup tables from the material system
        prepreg_er: dict[str, float] = {}
        core_er_by_thickness: dict[float, float] = {}
        if mat:
            template["material_system"] = {
                "name": mat.name,
                "manufacturer": mat.manufacturer,
            }
            for pp in mat.prepregs:
                prepreg_er[pp.type_name] = pp.er
            for core in mat.cores:
                core_er_by_thickness[core.thickness_mm] = core.er

        # Enhance each layer
        for layer in template.get("layers", []):
            if layer["type"] == "prepreg":
                type_name = _prepreg_type_name(layer.get("material", ""))
                er = prepreg_er.get(type_name)
                if er is not None:
                    layer["er"] = er

            elif layer["type"] == "core":
                thickness = _parse_thickness_mm(layer.get("thickness_mm", ""))
                if thickness is not None:
                    # Find closest core thickness match
                    best_er = core_er_by_thickness.get(thickness)
                    if best_er is None and core_er_by_thickness:
                        closest = min(
                            core_er_by_thickness,
                            key=lambda t, th=thickness: abs(t - th),
                        )
                        best_er = core_er_by_thickness[closest]
                    if best_er is not None:
                        layer["er"] = best_er

            elif layer["type"] == "copper":
                layer_name = layer.get("layer", "")
                is_outer = "Top" in layer_name or "Bottom" in layer_name
                layer["position"] = "external" if is_outer else "internal"

                thickness = _parse_thickness_mm(layer.get("thickness_mm", ""))
                if thickness is not None:
                    # Match against specs for the correct position
                    candidates = [
                        cs for cs in COPPER_SPECS if cs.position == layer["position"]
                    ]
                    best = min(
                        candidates,
                        key=lambda cs, th=thickness: abs(cs.thickness_mm - th),
                        default=None,
                    )
                    if best is not None:
                        layer["weight_oz"] = best.weight_oz

        # Add solder mask and trace geometry info
        template["solder_mask"] = {
            "base_thickness_mil": SOLDER_MASK.base_thickness_mil,
            "over_copper_thickness_mil": SOLDER_MASK.over_copper_thickness_mil,
            "between_traces_thickness_mil": SOLDER_MASK.between_traces_thickness_mil,
            "er": SOLDER_MASK.er,
        }
        template["trace_geometry"] = {
            "top_width_offset_mil": TRACE_GEOMETRY.top_width_offset_mil,
        }

    return templates


def _fetch_raw(output_dir: Path) -> None:
    """Fetch all stackup combos from JLCPCB and save raw JSON."""
    output_dir.mkdir(parents=True, exist_ok=True)

    total = sum(
        len(thicknesses) * len(OUTER_COPPER_WEIGHTS) * len(INNER_COPPER_WEIGHTS)
        for thicknesses in THICKNESS_MAP.values()
    )
    last_request_time = 0.0
    total_templates = 0

    progress = Progress(BarColumn(), MofNCompleteColumn(), TimeRemainingColumn())
    status_text = Text("")

    with Live(Group(progress, status_text), refresh_per_second=10):
        task = progress.add_task("Fetching", total=total)
        with httpx.Client(timeout=30) as client:
            for layer_count, thicknesses in sorted(THICKNESS_MAP.items()):
                for board_thickness in thicknesses:
                    for outer_cu in OUTER_COPPER_WEIGHTS:
                        for inner_cu in INNER_COPPER_WEIGHTS:
                            # Rate limit
                            elapsed = time.monotonic() - last_request_time
                            if elapsed < MIN_REQUEST_INTERVAL:
                                time.sleep(MIN_REQUEST_INTERVAL - elapsed)

                            payload = {
                                "stencilLayer": layer_count,
                                "stencilPly": board_thickness,
                                "cuprumThickness": outer_cu,
                                "insideCuprumThickness": inner_cu,
                            }

                            last_request_time = time.monotonic()
                            resp = client.post(API_URL, json=payload)
                            resp.raise_for_status()
                            data = resp.json()

                            fname = (
                                f"jlcpcb_{layer_count}L"
                                f"_{board_thickness}mm"
                                f"_outer{outer_cu}oz"
                                f"_inner{inner_cu}oz"
                                f".json"
                            )
                            (output_dir / fname).write_text(
                                json.dumps(data, indent=2) + "\n"
                            )

                            templates = data.get("data") or []
                            total_templates += len(templates)
                            progress.update(task, advance=1)
                            status_text.truncate(0)
                            status_text.append(f"{fname} ({len(templates)} templates)")

    typer.echo(f"{total} files, {total_templates} stackups written to {output_dir}/")


def _clean_all(raw_dir: Path, clean_dir: Path) -> None:
    """Read all raw JSON files and write cleaned versions."""
    clean_dir.mkdir(parents=True, exist_ok=True)

    raw_files = sorted(raw_dir.glob("jlcpcb_*.json"))
    if not raw_files:
        typer.echo(f"No raw JSON files found in {raw_dir}/")
        raise typer.Exit(1)

    total_templates = 0
    progress = Progress(BarColumn(), MofNCompleteColumn(), TimeRemainingColumn())
    status_text = Text("")

    with Live(Group(progress, status_text), refresh_per_second=10):
        task = progress.add_task("Cleaning", total=len(raw_files))
        for raw_file in raw_files:
            raw = json.loads(raw_file.read_text())
            cleaned = clean_data(raw)
            total_templates += len(cleaned)

            (clean_dir / raw_file.name).write_text(json.dumps(cleaned, indent=2) + "\n")

            progress.update(task, advance=1)
            status_text.truncate(0)
            status_text.append(f"{raw_file.name} ({len(cleaned)} templates)")

    typer.echo(
        f"{len(raw_files)} files, {total_templates} stackups written to {clean_dir}/"
    )


def _enhance_all(clean_dir: Path, enhanced_dir: Path) -> None:
    """Read cleaned JSON files and write enhanced versions with material properties."""
    enhanced_dir.mkdir(parents=True, exist_ok=True)

    clean_files = sorted(clean_dir.glob("jlcpcb_*.json"))
    if not clean_files:
        typer.echo(f"No cleaned JSON files found in {clean_dir}/")
        raise typer.Exit(1)

    total_templates = 0
    progress = Progress(BarColumn(), MofNCompleteColumn(), TimeRemainingColumn())
    status_text = Text("")

    with Live(Group(progress, status_text), refresh_per_second=10):
        task = progress.add_task("Enhancing", total=len(clean_files))
        for clean_file in clean_files:
            templates = json.loads(clean_file.read_text())
            enhanced = enhance_data(templates)
            total_templates += len(enhanced)

            (enhanced_dir / clean_file.name).write_text(
                json.dumps(enhanced, indent=2) + "\n"
            )

            progress.update(task, advance=1)
            status_text.truncate(0)
            status_text.append(f"{clean_file.name} ({len(enhanced)} templates)")

    typer.echo(
        f"{len(clean_files)} files, {total_templates} stackups written to "
        f"{enhanced_dir}/"
    )


_LAYER_TYPE_MAP = {
    "copper": "COPPER",
    "prepreg": "SUBSTRATE",
    "core": "CORE",
}

_MATERIAL_MAP = {
    "copper": "COPPER",
    "prepreg": "FR4",
    "core": "FR4",
}


def _format_thickness(thickness_str: str) -> str:
    """
    Format thickness string like '0.21040mm' into clean .ato value like '0.2104mm'.
    """
    m = re.match(r"([\d.]+)\s*mm", thickness_str)
    if not m:
        return thickness_str
    val = float(m.group(1))
    # Use up to 5 decimal places, strip trailing zeros
    formatted = f"{val:.5f}".rstrip("0").rstrip(".")
    return f"{formatted}mm"


def _sanitize_name(name: str) -> str:
    """Turn a template name like 'JLC04161H-7628' into a valid .ato identifier."""
    return re.sub(r"[^A-Za-z0-9_]", "_", name)


def _generate_module(template: dict[str, Any]) -> str:
    """Generate a single .ato module block from an enhanced template."""
    name = _sanitize_name(template["template_name"])
    layers = template["layers"]
    n = len(layers)
    layer_count = template.get("layer_count", "?")
    board_thickness = template.get("board_thickness_mm", "?")

    is_default = (
        template.get("is_default") is True
        and template.get("expedited") is False
        and template.get("enabled") is True
    )

    lines = [
        f"module {name} from PCBoard:",
        f'    """JLCPCB {layer_count}-layer {board_thickness}mm stackup."""',
        "    default: bool",
        f"    default = {is_default}",
        f"    stackup = new PCBLayer[{n}]",
        "",
        "    # layer_type (top to bottom)",
    ]

    for i, layer in enumerate(layers):
        lt = _LAYER_TYPE_MAP.get(layer["type"], "COPPER")
        lines.append(f'    stackup[{i}].layer_type = "{lt}"')

    lines.append("")
    lines.append("    # thickness")
    for i, layer in enumerate(layers):
        th = _format_thickness(layer.get("thickness_mm", "0mm"))
        lines.append(f"    stackup[{i}].thickness = {th}")

    lines.append("")
    lines.append("    # material")
    for i, layer in enumerate(layers):
        mat = _MATERIAL_MAP.get(layer["type"], "FR4")
        lines.append(f'    stackup[{i}].material = "{mat}"')

    # epsilon_r for dielectric layers only
    er_lines = []
    for i, layer in enumerate(layers):
        if layer["type"] in ("prepreg", "core") and "er" in layer:
            er_lines.append(f"    stackup[{i}].epsilon_r = {layer['er']}")
    if er_lines:
        lines.append("")
        lines.append("    # epsilon_r (dielectric layers)")
        lines.extend(er_lines)

    return "\n".join(lines)


def _export_ato(enhanced_dir: Path, output_path: Path) -> None:
    """Read enhanced JSON files and generate a single .ato file with all stackups."""
    enhanced_files = sorted(enhanced_dir.glob("jlcpcb_*.json"))
    if not enhanced_files:
        typer.echo(f"No enhanced JSON files found in {enhanced_dir}/")
        raise typer.Exit(1)

    # Collect all templates, deduplicate by template_name (keep first occurrence)
    seen: set[str] = set()
    unique_templates: list[dict[str, Any]] = []

    for f in enhanced_files:
        templates = json.loads(f.read_text())
        for t in templates:
            name = t.get("template_name", "")
            if name and name not in seen:
                seen.add(name)
                unique_templates.append(t)

    # Sort alphabetically by template name
    unique_templates.sort(key=lambda t: t["template_name"])

    # Generate .ato file
    header = "import PCBoard\nimport PCBLayer\n"
    modules = [_generate_module(t) for t in unique_templates]

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(header + "\n" + "\n\n".join(modules) + "\n")

    typer.echo(f"{len(unique_templates)} stackup modules written to {output_path}")


@app.command()
def main(
    output_dir: Path = typer.Option(
        Path("."),
        "--output-dir",
        "-o",
        help=(
            "Base output directory. Stackup data is written to "
            "<output-dir>/jlcpcb_stackups/{raw,cleaned,enhanced}/."
        ),
    ),
    fetch: bool = typer.Option(
        False, "--fetch", help="Fetch raw JSON from JLCPCB API."
    ),
    clean: bool = typer.Option(
        False, "--clean", help="Clean raw JSON into normalized stackups."
    ),
    enhance: bool = typer.Option(
        False, "--enhance", help="Enhance cleaned JSON with material properties."
    ),
    export: bool = typer.Option(
        False, "--export", help="Export enhanced JSON to a single .ato file."
    ),
    export_path: Path = typer.Option(
        Path("../../src/faebryk/library/JLCPCB.ato"),
        "--export-path",
        help="Output path for the generated .ato file.",
    ),
) -> None:
    """Fetch and/or clean JLCPCB stackup data."""
    if not fetch and not clean and not enhance and not export:
        typer.echo("Nothing to do. Pass --fetch, --clean, --enhance, and/or --export.")
        raise typer.Exit(1)

    base = output_dir / "jlcpcb_stackups"
    raw_dir = base / "raw"
    clean_dir = base / "cleaned"
    enhanced_dir = base / "enhanced"

    if fetch:
        typer.echo(
            f"{'-' * 20} Fetching raw stackups from JLCPCB API {'-' * 20}\n→ {raw_dir}/"
        )
        _fetch_raw(raw_dir)
        typer.echo(f"{'-' * 80}\n")

    if clean:
        typer.echo(f"{'-' * 28} Cleaning raw stackups {'-' * 28}\n→ {clean_dir}/")
        _clean_all(raw_dir, clean_dir)
        typer.echo(f"{'-' * 80}\n")

    if enhance:
        typer.echo(
            f"{'-' * 17} Enhancing stackups with material properties {'-' * 18}\n"
            f"→ {enhanced_dir}/"
        )
        _enhance_all(clean_dir, enhanced_dir)
        typer.echo(f"{'-' * 80}\n")

    if export:
        typer.echo(f"{'-' * 22} Exporting stackups to .ato {'-' * 22}\n→ {export_path}")
        _export_ato(enhanced_dir, export_path)
        typer.echo(f"{'-' * 80}")


if __name__ == "__main__":
    app()
