from faebryk.core.zig.gen.graph.graph import Literal, Node

class NodeCreationAttributes:
    @staticmethod
    def init(*, dynamic: dict[str, Literal] | None = ...) -> "NodeCreationAttributes": ...
    def apply_to(self, *, node: Node) -> None: ...
