from faebryk.core.zig.gen.faebryk.edgebuilder import EdgeCreationAttributes
from faebryk.core.zig.gen.graph.graph import BoundEdge, BoundNode, Edge, Node

class EdgePointer:
    @staticmethod
    def create(*, from_node: Node, to_node: Node, identifier: str) -> Edge: ...
    @staticmethod
    def build() -> EdgeCreationAttributes: ...
    @staticmethod
    def is_instance(*, edge: Edge) -> bool: ...
    @staticmethod
    def get_referenced_node(*, edge: Edge) -> Node | None: ...
    @staticmethod
    def get_referenced_node_from_node(*, node: BoundNode) -> BoundNode | None: ...
    @staticmethod
    def get_tid() -> Edge.Type: ...
    @staticmethod
    def point_to(*, bound_node: BoundNode, target_node: Node) -> BoundEdge: ...
