from faebryk.core.zig.gen.graph.graph import BoundNode, Edge, Node

class TypeGraph:
    @staticmethod
    def create() -> "TypeGraph": ...
    def add_type(self, *, identifier: str) -> BoundNode: ...
    def add_trait(self) -> BoundNode: ...
    def add_make_child(
        self, *, type_node: BoundNode, child_type_node: BoundNode, identifier: str
    ) -> BoundNode: ...
    def add_reference(self, *, type_node: BoundNode | None = None) -> BoundNode: ...
    def add_make_link(
        self,
        *,
        lhs_reference_node: Node,
        rhs_reference_node: Node,
        link_type: Edge.Type,
    ) -> BoundNode: ...
    def instantiate(self, *, type_identifier: str) -> BoundNode: ...
    def reference_resolve(
        self, *, reference_node: BoundNode, base_node: BoundNode
    ) -> BoundNode: ...
