from faebryk.core.zig.gen.graph.graph import BoundNode, Node

class TypeGraph:
    @staticmethod
    def create() -> "TypeGraph": ...
    def init_type_node(self, *, identifier: str) -> BoundNode: ...
    def init_trait_node(self) -> BoundNode: ...
    def init_make_child_node(
        self, *, type_node: BoundNode, identifier: str
    ) -> BoundNode: ...
    def init_reference_node(
        self, *, type_node: BoundNode | None = None
    ) -> BoundNode: ...
    def init_make_link_node(
        self,
        *,
        lhs_target_node: Node,
        rhs_target_node: Node,
        connection_identifier: str,
    ) -> BoundNode: ...
    def instantiate(self, *, build_target_type_identifier: str) -> BoundNode: ...
    def resolve_instance_reference(
        self, *, reference_node: BoundNode, base_node: BoundNode
    ) -> BoundNode: ...
