from faebryk.core.zig.gen.graph.graph import BoundNode, GraphView, Node


class TypeGraph:
    @staticmethod
    def create() -> "TypeGraph": ...

    def init_type_node(self) -> BoundNode: ...

    def init_trait_node(self) -> BoundNode: ...

    def init_make_child_node(self, *, type_node: BoundNode, identifier: str) -> BoundNode: ...

    def init_reference_node(self, *, type_node: BoundNode | None = None) -> BoundNode: ...

    def init_make_link_node(self) -> BoundNode: ...

    def instantiate(self, *, type_node: Node, graph_view: GraphView | None = None) -> BoundNode: ...

    def resolve_instance_reference(self, *, reference_node: BoundNode, base_node: BoundNode) -> BoundNode | None: ...
