name: debug

on:
  push:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - uses: tailscale/github-action@v3
        with:
            oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
            oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
            tags: tag:ci

      - uses: actions/checkout@v4

      # Required due to a bug in the checkout action
      # https://github.com/actions/checkout/issues/1471
      - run: git fetch --prune --unshallow --tags

      - uses: astral-sh/setup-uv@v5
        with:
          version: 0.6.4
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - uses: jwlawson/actions-setup-cmake@v2

      - run: >
          uv run --dev --no-editable --frozen
          ato --non-interactive package publish
          --registry http://100.75.32.89:8000/
