name: docs
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
  release:
    types: [published]

permissions:
  contents: write

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for mike to work with git history

      - name: Check Links
        uses: lycheeverse/lychee-action@v2
        with:
          args: -c docs/lychee.toml docs/

      - name: Spellcheck
        uses: streetsidesoftware/cspell-action@v6
        with:
          files: docs/**/*.md

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: '0.6.4'
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - run: uv run mkdocs build --strict

  deploy:
    if: (github.event_name == 'push' && github.event.ref == 'refs/heads/main') || (github.event_name == 'release' && !github.event.release.draft)
    environment: github-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for mike to work with git history

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: '0.6.4'
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Get version
        id: get_version
        run: |
          VERSION=$(uv run ato --version)
          MAJOR_MINOR=$(echo $VERSION | cut -d. -f1,2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "MAJOR_MINOR=$MAJOR_MINOR" >> $GITHUB_ENV

      - name: Deploy development docs
        if: github.event_name == 'push' && github.event.ref == 'refs/heads/main'
        # TODO: it'd be nice to have the upcoming version number here as well
        # but it clobbers the latest release in case they're the same
        run: uv run mike deploy --push --update-aliases dev

      - name: Deploy release docs
        if: github.event_name == 'release' && !github.event.release.prerelease && !github.event.release.draft
        run: uv run mike deploy --push --update-aliases $MAJOR_MINOR latest
