# https://github.com/actions/labeler
name: "Pull Request Labeler Test"
on:
#  - pull_request_target
  #TODO remove
  - push

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          sync-labels: true
          pr-number: 1159
