name: Continuous Integration

on: push

jobs:
  regression_tests:
    runs-on: ubuntu-latest
    env:
        ATO_NON_INTERACTIVE: '1'
        SETUPTOOLS_SCM_PRETEND_VERSION: "0.2.45"
    strategy:
      fail-fast: false
      matrix:
        repo: [
          'atopile/swoop',
          'atopile/spin-servo-drive'
        ]
    steps:
      - uses: actions/checkout@v4
      - name: Get latest released tag
        run: |
          LATEST_TAG=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/releases/latest" \
              | jq -r .tag_name)
          echo "SETUPTOOLS_SCM_PRETEND_VERSION=$LATEST_TAG" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -e .

      - name: Checkout circuit repository
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repo }}
          path: 'circuit_repo'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build circuits
        run: |
          cd circuit_repo
          ato build
