name: Continuous Integration

on: push

jobs:
  regression_tests:
    runs-on: ubuntu-latest
    env:
      ATO_NON_INTERACTIVE: '1'
      fail-fast: false
    strategy:
      matrix:
        repo: [
          'atopile/swoop',
          'atopile/spin-servo-drive'
        ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
        env:
          SETUPTOOLS_SCM_PRETEND_VERSION: ${{ steps.tag_name.outputs.tag }}

      - name: Install dependencies
        run: pip install -e .

      - name: Checkout circuit repository
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repo }}
          path: 'circuit_repo'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build circuits
        run: |
          cd circuit_repo
          ato build
