name: website
on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check Links
        uses: lycheeverse/lychee-action@v2
        with:
          args: docs/

      - name: Spellcheck
        uses: streetsidesoftware/cspell-action@v6
        with:
          files: docs/**/*.md

  deploy:
    runs-on: ubuntu-latest
    needs: tests
    environment: github-pages
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for mike to work with git history

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: '0.6.4'
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Get version
        id: get_version
        run: |
          VERSION=$(uv run ato --version)
          MAJOR_MINOR=$(echo $VERSION | cut -d. -f1,2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "MAJOR_MINOR=$MAJOR_MINOR" >> $GITHUB_ENV

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.WEBSITE_DEPLOYER_APP_ID }}
          private-key: ${{ secrets.WEBSITE_DEPLOYER_KEY }}

      - name: Deploy development docs
        if: github.event_name == 'push' && github.event.ref == 'main'
        # TODO: it'd be nice to have the upcoming version number here as well
        # but it clobbers the latest release in case they're the same
        run: uv run mike deploy --push --remote "https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/${{ github.repository }}" --update-aliases dev

      - name: Deploy release docs
        if: github.event_name == 'release' && !github.event.release.prerelease && !github.event.release.draft
        run: uv run mike deploy --push --remote "https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/${{ github.repository }}" --update-aliases $MAJOR_MINOR latest
