# This file is part of the faebryk project
# SPDX-License-Identifier: MIT

# This file is auto-generated by zig.
# Do not edit this file directly; edit the corresponding
# Zig file instead.

class Nested:
    x: int
    y: str

    def __init__(self, x: int, y: str) -> None: ...
    def __repr__(self) -> str: ...

class Top:
    a: int
    b: int
    c: Nested

    def __init__(self, a: int, b: int, c: Nested) -> None: ...
    def __repr__(self) -> str: ...
    def sum(self) -> int: ...

def add(*, a: int, b: int) -> int: ...
def get_default_top() -> Top: ...
