# This file is part of the faebryk project
# SPDX-License-Identifier: MIT

# This file is auto-generated by zig.
# Do not edit this file directly; edit the corresponding
# Zig file instead.

from typing import Any  # noqa: F401

from faebryk.core.zig.schematic import Symbol

# Dirty hack to not error in ruff check
type Allocator = Any

class SymbolLib:
    version: int
    generator: str
    symbols: list[Symbol]

    def __init__(self, version: int, generator: str, symbols: list[Symbol]) -> None: ...
    def __repr__(self) -> str: ...

class SymbolFile:
    kicad_sym: SymbolLib

    def __init__(self, kicad_sym: SymbolLib) -> None: ...
    def __repr__(self) -> str: ...
    def free(self, arg_0: Allocator) -> None: ...

# Module-level functions
def loads(data: str) -> SymbolFile: ...
def dumps(obj: SymbolFile) -> str: ...
